create table if not exists users
(
    id       bigint generated by default as identity
        constraint users_pkey
            primary key,
    password varchar(255),
    username varchar(255)
);


create table if not exists roles
(
    id   bigint generated by default as identity
        constraint roles_pkey
            primary key,
    name varchar(255)
);

create table if not exists users_roles
(
    user_id bigint not null
        constraint fk2o0jvgh89lemvvo17cbqvdxaa
            references users,
    role_id bigint not null
        constraint fkj6m8fwv7oqv74fcehir1a9ffy
            references roles
);

insert into users(id, username, password)
values (1, 'user', '$2a$10$uFlxQ97X5XseOiGibBUsP.yNnuhDO8fx46vF/h/tNN46kXPbAzaQK'); /* password = user*/

insert into roles(id, name)
values (1, 'ROLE_USER'); /* password = user*/

insert into users_roles(user_id, role_id)
values (1, 1);
