name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -f backend --batch-mode --update-snapshots verify
      - name: Get Allure history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: backend/allure-results
      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          destination_dir: allure

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install dependencies
        run: npm --prefix client install
      - name: Build
        run: npm --prefix client run build
      - name: Test
        run: npm --prefix client test -- --configuration=ci
      - name: E2E
        run: npm --prefix client run e2e -- --configuration=ci
